const sharedLinks = {
  support: "/soporte-tecnico-empresas/",
  cyber: "/auditoria-ciberseguridad-nist/",
  servers: "/administracion-servidores/",
  equipment: "/equipos-componentes/",
  web: "/desarrollo-web-empresarial/",
  seo: "/seo-mexico/",
} as const;

const homeByLanguage = {
  "es-MX": {
    intro: ["IATERA", "Infraestructura tecnológica empresarial", "Integramos soporte TI, infraestructura y ciberseguridad para que las empresas en México puedan resolver incidentes, mantener sus sistemas disponibles y tomar decisiones técnicas con información clara."],
    servicesKicker: "Cuatro pilares",
    servicesTitle: "La tecnología que sostiene tu operación.",
    learnMore: "Conocer el servicio",
    pillars: [
      ["Soporte técnico y Help Desk", "Atendemos incidentes técnicos de usuarios y equipos mediante soporte remoto o asistencia en sitio. Cada solicitud se registra, se prioriza y se documenta para mantener la continuidad de la operación. Así, el equipo interno conserva visibilidad sobre el avance y los pendientes.", ["Atención remota y en sitio", "Prioridad según impacto", "Cierre documentado"], sharedLinks.support],
      ["Ciberseguridad con prioridades claras", "Evaluamos accesos, correo, dispositivos, red, respaldos y controles críticos para identificar los riesgos que realmente pueden afectar la operación. IATERA entrega hallazgos priorizados y un plan de mejora comprensible para dirección y equipos técnicos. Así, las decisiones de inversión se apoyan en evidencia y no en alarmas genéricas.", ["Riesgos priorizados", "Lectura ejecutiva y técnica", "Plan de mejora aplicable"], sharedLinks.cyber],
      ["Infraestructura y servidores", "Administramos servidores Windows, Linux, cloud y on-premise con rutinas de monitoreo, respaldos, actualización y seguimiento. El objetivo es reducir interrupciones y mantener una infraestructura tecnológica empresarial ordenada, visible y preparada para crecer, sin perder trazabilidad interna de los cambios realizados.", ["Monitoreo operativo", "Respaldos verificados", "Seguimiento de alertas"], sharedLinks.servers],
      ["Equipos, componentes y mantenimiento", "Diagnosticamos, reparamos y mantenemos equipos de trabajo, además de suministrar componentes compatibles y equipos adecuados para cada necesidad. Antes de recomendar una compra, revisamos el uso, la capacidad requerida y las opciones de recuperación para evitar gastos innecesarios o reemplazos prematuros.", ["Diagnóstico antes de reemplazar", "Compatibilidad validada", "Instalación y pruebas"], sharedLinks.equipment],
      ["Desarrollo web empresarial", "Diseñamos páginas web empresariales claras, rápidas y responsive, con una arquitectura mantenible y una base técnica preparada para crecer.", ["Arquitectura orientada a negocio", "Responsive y accesible", "Rendimiento verificable"], sharedLinks.web],
      ["SEO en México", "Mejoramos la base técnica, la arquitectura y el contenido para conectar los servicios reales de la empresa con búsquedas relevantes en México.", ["Diagnóstico técnico", "Contenido por intención", "Medición comprensible"], sharedLinks.seo],
    ],
    cyberTitle: "Ciberseguridad con prioridades claras",
    cyberText: "Evaluamos accesos, correo, dispositivos, red, respaldos y controles críticos para identificar los riesgos que realmente pueden afectar la operación. IATERA entrega hallazgos priorizados y un plan de mejora comprensible para dirección y equipos técnicos.",
    cyberCta: "Conocer la auditoría de ciberseguridad",
    trustKicker: "Trabajo verificable",
    trustTitle: "Claridad antes, durante y después del servicio.",
    trustItems: [["Alcance definido", "Acordamos qué se revisará, qué acceso se necesita y cuál es el resultado esperado."], ["Evidencia útil", "Registramos hallazgos, acciones realizadas y pendientes sin inflar métricas ni promesas."], ["Cobertura flexible", "Atención remota en México y visitas en Ciudad de México y Estado de México, según alcance."]],
    coverageKicker: "Cobertura",
    coverageTitle: "Soporte donde opera tu empresa.",
    coverageText: "Atendemos de forma remota a empresas en México y coordinamos asistencia en sitio en Ciudad de México y Estado de México. La modalidad se define según el incidente, los accesos disponibles y la necesidad de intervención física.",
  },
  en: {
    intro: ["IATERA", "Enterprise technology infrastructure", "We bring together IT support, infrastructure and cybersecurity so companies in Mexico can resolve incidents, keep systems available and make technical decisions with clear information."],
    servicesKicker: "Four pillars", servicesTitle: "Technology that supports your operation.", learnMore: "Explore the service",
    pillars: [["Technical support and Help Desk", "We handle user and equipment incidents through remote support or on-site assistance. Every request is logged, prioritized and documented to protect operational continuity.", ["Remote and on-site support", "Impact-based priority", "Documented closure"], sharedLinks.support], ["Business cybersecurity", "We review critical access, email, devices, networks, backups and controls to identify the risks that could affect operations, then provide prioritized findings and a clear improvement plan.", ["Prioritized risks", "Executive and technical view", "Practical improvement plan"], sharedLinks.cyber], ["Infrastructure and servers", "We manage Windows, Linux, cloud and on-premise servers through monitoring, backup, update and follow-up routines designed to reduce disruption and improve visibility.", ["Operational monitoring", "Verified backups", "Alert follow-up"], sharedLinks.servers], ["Equipment, components and maintenance", "We diagnose, repair and maintain business equipment, and supply compatible components or suitable devices after reviewing actual workload and recovery options.", ["Diagnosis before replacement", "Validated compatibility", "Installation and testing"], sharedLinks.equipment], ["Business web development", "We build clear, responsive and maintainable business websites with performance, accessibility and technical SEO foundations.", ["Business-led architecture", "Responsive and accessible", "Measurable performance"], sharedLinks.web], ["SEO in Mexico", "We improve technical foundations, information architecture and useful content to connect real services with relevant searches in Mexico.", ["Technical diagnosis", "Intent-led content", "Clear measurement"], sharedLinks.seo]],
    cyberTitle: "Cybersecurity with clear priorities", cyberText: "We review access, email, devices, networks, backups and critical controls to identify the risks that can actually affect operations. IATERA provides prioritized findings and an improvement plan that leadership and technical teams can understand.", cyberCta: "Explore the cybersecurity audit",
    trustKicker: "Verifiable work", trustTitle: "Clarity before, during and after service.", trustItems: [["Defined scope", "We agree on the review, required access and expected outcome."], ["Useful evidence", "We document findings, completed actions and pending work without inflated claims."], ["Flexible coverage", "Remote support in Mexico and on-site visits in Mexico City and the State of Mexico, depending on scope."]],
    coverageKicker: "Coverage", coverageTitle: "Support where your company operates.", coverageText: "We support companies remotely across Mexico and coordinate on-site assistance in Mexico City and the State of Mexico. The service mode depends on the incident and whether physical intervention is required.",
  },
  fr: {
    intro: ["IATERA", "Infrastructure technologique d’entreprise", "Nous réunissons support IT, infrastructure et cybersécurité pour aider les entreprises au Mexique à résoudre les incidents et prendre des décisions techniques claires."], servicesKicker: "Quatre piliers", servicesTitle: "La technologie qui soutient vos opérations.", learnMore: "Découvrir le service",
    pillars: [["Support technique et Help Desk", "Nous traitons les incidents utilisateurs et matériels à distance ou sur site. Chaque demande est enregistrée, priorisée et documentée pour préserver la continuité.", ["À distance et sur site", "Priorité selon l’impact", "Clôture documentée"], sharedLinks.support], ["Cybersécurité d’entreprise", "Nous évaluons les accès, emails, appareils, réseaux, sauvegardes et contrôles critiques, puis livrons des constats priorisés et un plan d’amélioration clair.", ["Risques priorisés", "Lecture direction et IT", "Plan applicable"], sharedLinks.cyber], ["Infrastructure et serveurs", "Nous administrons les serveurs Windows, Linux, cloud et sur site avec suivi, sauvegardes et mises à jour pour réduire les interruptions.", ["Suivi opérationnel", "Sauvegardes vérifiées", "Suivi des alertes"], sharedLinks.servers], ["Équipements, composants et maintenance", "Nous diagnostiquons, réparons et entretenons les équipements, puis proposons des composants compatibles selon les besoins réels.", ["Diagnostic préalable", "Compatibilité vérifiée", "Installation testée"], sharedLinks.equipment], ["Développement web d’entreprise", "Nous créons des sites clairs, responsive et maintenables, avec de bonnes bases de performance, d’accessibilité et de SEO technique.", ["Architecture métier", "Responsive et accessible", "Performance mesurable"], sharedLinks.web], ["SEO au Mexique", "Nous améliorons la base technique, l’architecture et le contenu utile pour relier les services réels aux recherches pertinentes au Mexique.", ["Diagnostic technique", "Contenu par intention", "Mesure claire"], sharedLinks.seo]],
    cyberTitle: "Une cybersécurité aux priorités claires", cyberText: "Nous évaluons les contrôles qui peuvent réellement affecter les opérations et livrons des constats priorisés ainsi qu’un plan compréhensible par la direction et les équipes techniques.", cyberCta: "Découvrir l’audit de cybersécurité", trustKicker: "Travail vérifiable", trustTitle: "De la clarté à chaque étape.", trustItems: [["Périmètre défini", "Objectif, accès et livrables sont convenus."], ["Preuves utiles", "Actions et points en attente sont documentés."], ["Couverture flexible", "Support à distance au Mexique et interventions locales selon le périmètre."]], coverageKicker: "Couverture", coverageTitle: "Un support adapté à votre implantation.", coverageText: "Support à distance au Mexique et interventions coordonnées à Mexico et dans l’État de Mexico selon la nature du besoin.",
  },
  de: {
    intro: ["IATERA", "Technologische Unternehmensinfrastruktur", "Wir verbinden IT-Support, Infrastruktur und Cybersicherheit, damit Unternehmen in Mexiko Störungen lösen und fundierte technische Entscheidungen treffen können."], servicesKicker: "Vier Säulen", servicesTitle: "Technologie, die Ihren Betrieb trägt.", learnMore: "Service ansehen",
    pillars: [["Technischer Support und Help Desk", "Wir bearbeiten Störungen von Nutzern und Geräten remote oder vor Ort. Jede Anfrage wird erfasst, priorisiert und dokumentiert.", ["Remote und vor Ort", "Priorität nach Auswirkung", "Dokumentierter Abschluss"], sharedLinks.support], ["Cybersicherheit für Unternehmen", "Wir prüfen kritische Zugänge, E-Mail, Geräte, Netzwerke und Backups und liefern priorisierte Befunde sowie einen klaren Verbesserungsplan.", ["Priorisierte Risiken", "Management- und IT-Sicht", "Umsetzbarer Plan"], sharedLinks.cyber], ["Infrastruktur und Server", "Wir verwalten Windows-, Linux-, Cloud- und lokale Server mit Monitoring, Backups und Updates, um Unterbrechungen zu reduzieren.", ["Betriebsmonitoring", "Geprüfte Backups", "Alarmverfolgung"], sharedLinks.servers], ["Geräte, Komponenten und Wartung", "Wir diagnostizieren, reparieren und warten Geräte und liefern kompatible Komponenten auf Basis des tatsächlichen Bedarfs.", ["Diagnose vor Austausch", "Geprüfte Kompatibilität", "Installation und Tests"], sharedLinks.equipment], ["Webentwicklung für Unternehmen", "Wir entwickeln klare, responsive und wartbare Unternehmenswebsites mit soliden Grundlagen für Leistung, Barrierefreiheit und technisches SEO.", ["Geschäftsorientierte Architektur", "Responsive und zugänglich", "Messbare Leistung"], sharedLinks.web], ["SEO in Mexiko", "Wir verbessern Technik, Informationsarchitektur und nützliche Inhalte, um reale Leistungen mit relevanten Suchanfragen zu verbinden.", ["Technische Analyse", "Inhalte nach Suchintention", "Klare Messung"], sharedLinks.seo]],
    cyberTitle: "Cybersicherheit mit klaren Prioritäten", cyberText: "Wir bewerten die Kontrollen, die den Betrieb tatsächlich beeinflussen können, und liefern priorisierte Befunde sowie einen verständlichen Verbesserungsplan.", cyberCta: "Cybersicherheitsaudit ansehen", trustKicker: "Nachvollziehbare Arbeit", trustTitle: "Klarheit in jeder Phase.", trustItems: [["Definierter Umfang", "Ziel, Zugänge und Ergebnis werden abgestimmt."], ["Nützliche Nachweise", "Maßnahmen und offene Punkte werden dokumentiert."], ["Flexible Abdeckung", "Remote-Support in Mexiko und lokale Einsätze nach Umfang."]], coverageKicker: "Abdeckung", coverageTitle: "Support an Ihrem Betriebsort.", coverageText: "Remote-Support in Mexiko sowie koordinierte Einsätze in Mexiko-Stadt und im Bundesstaat Mexiko.",
  },
  pt: {
    intro: ["IATERA", "Infraestrutura tecnológica empresarial", "Integramos suporte de TI, infraestrutura e cibersegurança para que empresas no México resolvam incidentes e tomem decisões técnicas com clareza."], servicesKicker: "Quatro pilares", servicesTitle: "A tecnologia que sustenta sua operação.", learnMore: "Conhecer o serviço",
    pillars: [["Suporte técnico e Help Desk", "Atendemos incidentes de usuários e equipamentos de forma remota ou presencial. Cada solicitação é registrada, priorizada e documentada.", ["Remoto e presencial", "Prioridade por impacto", "Fechamento documentado"], sharedLinks.support], ["Cibersegurança empresarial", "Avaliamos acessos, e-mail, dispositivos, rede, backups e controles críticos, entregando achados priorizados e um plano claro de melhoria.", ["Riscos priorizados", "Visão executiva e técnica", "Plano aplicável"], sharedLinks.cyber], ["Infraestrutura e servidores", "Administramos servidores Windows, Linux, cloud e on-premise com monitoramento, backups e atualizações para reduzir interrupções.", ["Monitoramento operacional", "Backups verificados", "Acompanhamento de alertas"], sharedLinks.servers], ["Equipamentos, componentes e manutenção", "Diagnosticamos, reparamos e mantemos equipamentos, além de fornecer componentes compatíveis com a necessidade real.", ["Diagnóstico prévio", "Compatibilidade validada", "Instalação e testes"], sharedLinks.equipment], ["Desenvolvimento web empresarial", "Criamos sites claros, responsivos e sustentáveis, com boas bases de desempenho, acessibilidade e SEO técnico.", ["Arquitetura de negócio", "Responsivo e acessível", "Desempenho mensurável"], sharedLinks.web], ["SEO no México", "Melhoramos a base técnica, a arquitetura e o conteúdo útil para conectar serviços reais a buscas relevantes no México.", ["Diagnóstico técnico", "Conteúdo por intenção", "Medição clara"], sharedLinks.seo]],
    cyberTitle: "Cibersegurança com prioridades claras", cyberText: "Avaliamos os controles que realmente podem afetar a operação e entregamos achados priorizados e um plano compreensível para a direção e as equipes técnicas.", cyberCta: "Conhecer a auditoria de cibersegurança", trustKicker: "Trabalho verificável", trustTitle: "Clareza em cada etapa.", trustItems: [["Escopo definido", "Objetivo, acessos e resultado são acordados."], ["Evidência útil", "Ações e pendências são documentadas."], ["Cobertura flexível", "Suporte remoto no México e atendimento local conforme o escopo."]], coverageKicker: "Cobertura", coverageTitle: "Suporte onde sua empresa opera.", coverageText: "Suporte remoto no México e atendimento coordenado na Cidade do México e no Estado do México.",
  },
  it: {
    intro: ["IATERA", "Infrastruttura tecnologica aziendale", "Uniamo supporto IT, infrastruttura e cybersicurezza per aiutare le aziende in Messico a risolvere gli incidenti e decidere con informazioni chiare."], servicesKicker: "Quattro pilastri", servicesTitle: "La tecnologia che sostiene le tue operazioni.", learnMore: "Scopri il servizio",
    pillars: [["Supporto tecnico e Help Desk", "Gestiamo incidenti di utenti e dispositivi da remoto o in sede. Ogni richiesta viene registrata, priorizzata e documentata.", ["Remoto e in sede", "Priorità per impatto", "Chiusura documentata"], sharedLinks.support], ["Cybersicurezza aziendale", "Valutiamo accessi, email, dispositivi, rete, backup e controlli critici, fornendo risultati prioritari e un piano chiaro.", ["Rischi prioritari", "Vista direzionale e tecnica", "Piano applicabile"], sharedLinks.cyber], ["Infrastruttura e server", "Gestiamo server Windows, Linux, cloud e on-premise con monitoraggio, backup e aggiornamenti per ridurre le interruzioni.", ["Monitoraggio operativo", "Backup verificati", "Gestione degli avvisi"], sharedLinks.servers], ["Dispositivi, componenti e manutenzione", "Diagnostichiamo, ripariamo e manteniamo i dispositivi e forniamo componenti compatibili con le esigenze reali.", ["Diagnosi preventiva", "Compatibilità verificata", "Installazione e test"], sharedLinks.equipment], ["Sviluppo web aziendale", "Realizziamo siti chiari, responsive e manutenibili, con solide basi di prestazioni, accessibilità e SEO tecnico.", ["Architettura orientata al business", "Responsive e accessibile", "Prestazioni misurabili"], sharedLinks.web], ["SEO in Messico", "Miglioriamo tecnica, architettura e contenuti utili per collegare servizi reali a ricerche pertinenti in Messico.", ["Diagnosi tecnica", "Contenuti per intento", "Misurazione chiara"], sharedLinks.seo]],
    cyberTitle: "Cybersicurezza con priorità chiare", cyberText: "Valutiamo i controlli che possono davvero influire sulle operazioni e forniamo risultati prioritari e un piano comprensibile per direzione e tecnici.", cyberCta: "Scopri l’audit di cybersicurezza", trustKicker: "Lavoro verificabile", trustTitle: "Chiarezza in ogni fase.", trustItems: [["Ambito definito", "Obiettivo, accessi e risultato vengono concordati."], ["Evidenze utili", "Azioni e attività aperte vengono documentate."], ["Copertura flessibile", "Supporto remoto in Messico e interventi locali secondo l’ambito."]], coverageKicker: "Copertura", coverageTitle: "Supporto dove opera la tua azienda.", coverageText: "Supporto remoto in Messico e assistenza coordinata a Città del Messico e nello Stato del Messico.",
  },
} as const;

export function getHomeCopy(langTag: string) {
  return homeByLanguage[langTag as keyof typeof homeByLanguage] ?? homeByLanguage["es-MX"];
}
