export interface ServicePageData {
  slug: string;
  eyebrow: string;
  title: string;
  description: string;
  intro: string;
  benefits: readonly [string, string][];
  sections: readonly { title: string; text: string; items?: readonly string[] }[];
  faq: readonly [string, string][];
  ctaTitle: string;
  ctaText: string;
  related: readonly string[];
}

export const servicePages: readonly ServicePageData[] = [
  {
    slug: "soporte-tecnico-empresas",
    eyebrow: "Soporte TI para empresas",
    title: "Soporte técnico para empresas en México",
    description: "Soporte técnico para empresas con Help Desk remoto y atención en sitio en CDMX y Estado de México. Incidentes registrados, priorizados y documentados.",
    intro: "IATERA atiende incidentes de usuarios, equipos y servicios tecnológicos sin convertir cada solicitud en una conversación aislada. Organizamos la atención por impacto, coordinamos soporte remoto o visita técnica y dejamos evidencia del trabajo para que la empresa recupere la operación y conserve el control.",
    benefits: [["Una entrada clara", "Las solicitudes se concentran, clasifican y asignan según su efecto en la operación."], ["La modalidad correcta", "Resolvemos a distancia cuando es posible y coordinamos atención en sitio cuando la falla requiere intervención física."], ["Historial útil", "Documentamos diagnóstico, acciones, resultado y recomendaciones para reducir incidentes repetidos."]],
    sections: [
      { title: "Help Desk enfocado en continuidad", text: "El soporte comienza por entender quién está detenido, qué proceso depende del equipo y qué alternativas existen. Esta evaluación permite atender primero lo que tiene mayor impacto, sin perder de vista solicitudes individuales.", items: ["Correo, aplicaciones y cuentas de usuario", "Accesos, VPN y conectividad", "Impresoras, periféricos y estaciones de trabajo"] },
      { title: "Soporte remoto o asistencia en sitio", text: "La conexión remota agiliza ajustes de software, configuración y diagnóstico. Cuando intervienen cableado, red local, componentes o fallas físicas, coordinamos una visita en Ciudad de México o Estado de México conforme al alcance acordado." },
      { title: "Del ticket al cierre documentado", text: "Cada solicitud sigue un flujo sencillo: registro, prioridad, diagnóstico, resolución y cierre. Si una causa requiere inversión, proveedor externo o una mejora posterior, queda señalada para que el responsable pueda decidir con contexto." },
    ],
    faq: [["¿Qué tipo de empresas pueden solicitar soporte?", "Atendemos PyMEs y empresas que necesitan apoyo para usuarios, equipos, aplicaciones, accesos y conectividad en México."], ["¿Todo se resuelve de forma remota?", "No. Priorizamos la vía remota cuando es segura y suficiente; coordinamos atención en sitio cuando existe una falla física o de infraestructura local."], ["¿Cómo se prioriza un incidente?", "Se consideran usuarios afectados, procesos detenidos, riesgo para la información y disponibilidad de una alternativa temporal."], ["¿El servicio incluye documentación?", "Sí. El cierre puede incluir causa encontrada, acciones realizadas, resultado, pendientes y recomendaciones."], ["¿Pueden apoyar a un equipo interno de TI?", "Sí. Podemos atender solicitudes operativas o casos específicos bajo un alcance coordinado con el responsable interno."]],
    ctaTitle: "Recupera la operación con un siguiente paso claro.", ctaText: "Describe el incidente, los usuarios afectados y la ubicación. Revisaremos la modalidad de atención adecuada.", related: ["administracion-servidores", "mantenimiento-equipos", "auditoria-ciberseguridad-nist"],
  },
  {
    slug: "auditoria-ciberseguridad-nist",
    eyebrow: "Auditoría de ciberseguridad",
    title: "Auditoría de ciberseguridad alineada a NIST CSF",
    description: "Auditoría de ciberseguridad para empresas en México: revisión alineada a NIST CSF, matriz de riesgos, capacitación y plan de mejora 30/60/90.",
    intro: "Una auditoría útil no entrega alarmas genéricas. IATERA revisa cómo se protegen accesos, correo, dispositivos, redes, respaldos y procesos críticos; relaciona la evidencia con el impacto de negocio y convierte los hallazgos en prioridades comprensibles para dirección y equipos técnicos.",
    benefits: [["Riesgo priorizado", "La matriz relaciona probabilidad, impacto operativo, urgencia y responsable sugerido."], ["Dos niveles de lectura", "El reporte ejecutivo facilita decisiones y el detalle técnico orienta la corrección."], ["Ruta de mejora", "El plan 30/60/90 separa acciones inmediatas, mejoras estructurales y seguimiento."]],
    sections: [
      { title: "Alcance basado en la operación real", text: "La revisión parte de los sistemas importantes, usuarios clave, sedes, proveedores y datos sensibles. Con ese contexto evaluamos controles relevantes sin repetir un checklist que trate a todas las empresas igual.", items: ["Identidad, privilegios y autenticación multifactor", "Correo, endpoints, red y servicios cloud", "Respaldos, políticas y respuesta a incidentes"] },
      { title: "Proceso de auditoría y entregables", text: "El proceso reúne contexto, evidencia técnica y entrevistas. Después priorizamos hallazgos, preparamos una matriz de riesgos y entregamos un reporte ejecutivo con recomendaciones, responsables sugeridos y criterios para validar avances." },
      { title: "Capacitación antiphishing", text: "Cuando el riesgo humano forma parte del alcance, diseñamos sesiones sobre phishing, contraseñas, MFA, información sensible y reporte de incidentes. La capacitación se vincula con situaciones reales de la empresa y no sustituye los controles técnicos." },
      { title: "Plan de mejora 30/60/90", text: "Los primeros 30 días se enfocan en exposiciones urgentes y ajustes de alto impacto. Los siguientes periodos ordenan controles que requieren coordinación, presupuesto, políticas, capacitación o validación técnica." },
      { title: "Niveles de servicio", text: "El alcance puede concentrarse en un diagnóstico inicial, una auditoría con plan de remediación o un programa que sume acompañamiento y capacitación. La profundidad se define después de conocer activos, sedes, exposición y evidencia disponible." },
      { title: "Cotizador express", text: "Para estimar el alcance consideramos número de equipos, sedes, servicios expuestos, tipo de información y madurez de los controles actuales. La referencia se confirma en una conversación técnica; no publicamos una cifra automática que ignore la complejidad real." },
    ],
    faq: [["¿Una auditoría NIST es una certificación?", "No. Esta evaluación usa el marco como referencia para ordenar funciones y controles; no se presenta como certificación ni acreditación oficial."], ["¿Qué información necesitan para comenzar?", "Un inventario básico, responsables, servicios críticos, incidentes conocidos y acceso a la evidencia acordada ayudan a definir el alcance."], ["¿La auditoría interrumpe la operación?", "Las revisiones se planifican para reducir impacto. Cualquier prueba que pueda afectar sistemas requiere autorización y coordinación previa."], ["¿Qué contiene la matriz de riesgos?", "Incluye el hallazgo, la evidencia, el escenario de riesgo, probabilidad, impacto, prioridad y recomendación."], ["¿Pueden ayudar después de entregar el reporte?", "Sí. El acompañamiento de remediación puede contratarse con alcance separado y criterios de cierre definidos."], ["¿La capacitación está incluida?", "Depende del nivel de servicio. Puede integrarse cuando las necesidades de concienciación forman parte del riesgo identificado."]],
    ctaTitle: "Convierte el riesgo en decisiones ejecutables.", ctaText: "Cuéntanos qué sistemas necesitas revisar y qué decisión debe apoyar la auditoría.", related: ["soporte-tecnico-empresas", "administracion-servidores", "mantenimiento-equipos"],
  },
  {
    slug: "administracion-servidores",
    eyebrow: "Infraestructura y servidores",
    title: "Administración de servidores para empresas",
    description: "Administración de servidores Windows, Linux, cloud y on-premise en México con monitoreo, respaldos, actualizaciones y seguimiento operativo.",
    intro: "IATERA ayuda a mantener servidores y servicios esenciales con rutinas definidas, visibilidad de alertas y cambios documentados. El trabajo se adapta a entornos Windows, Linux, cloud u on-premise y comienza por entender qué procesos dependen de cada sistema.",
    benefits: [["Operación visible", "Inventario, responsables, alertas y tareas recurrentes se organizan en un mismo esquema."], ["Cambios controlados", "Actualizaciones y ajustes se planifican con validaciones y criterios de reversa."], ["Recuperación preparada", "Los respaldos se revisan por cobertura, frecuencia, retención y posibilidad de restauración."]],
    sections: [{ title: "Administración según la criticidad", text: "No todos los servidores requieren la misma frecuencia de revisión. Definimos prioridades según servicios alojados, usuarios afectados, exposición y ventanas disponibles.", items: ["Windows Server y Linux", "Servicios cloud y máquinas virtuales", "Infraestructura local y servicios híbridos"] }, { title: "Monitoreo y gestión de alertas", text: "El monitoreo debe terminar en una acción. Acordamos qué señales observar, quién recibe la alerta, cuándo escalar y qué información registrar para evitar paneles sin seguimiento." }, { title: "Respaldos, parches y mantenimiento", text: "Revisamos que las copias cubran la información necesaria y que exista una ruta de restauración. Las actualizaciones se ordenan por riesgo, dependencia y ventana de mantenimiento, con registro de resultados y pendientes." }, { title: "Documentación para continuidad", text: "La información operativa incluye inventario, accesos administrados, servicios, tareas recurrentes, dependencias y contactos. Se entrega conforme al alcance y sin exponer credenciales en documentos inseguros." }],
    faq: [["¿Administran servidores físicos y virtuales?", "Sí, el alcance puede cubrir infraestructura física, máquinas virtuales y servicios cloud."], ["¿Incluye monitoreo permanente?", "La frecuencia y los horarios se definen en la propuesta; no prometemos cobertura continua sin un acuerdo específico."], ["¿Cómo validan los respaldos?", "Se revisan registros, cobertura, retención y, cuando se autoriza, pruebas de restauración controladas."], ["¿Pueden trabajar con nuestro proveedor cloud?", "Sí, siempre que existan accesos autorizados y responsabilidades claramente delimitadas."], ["¿Realizan hardening?", "Puede incluirse después de revisar compatibilidad, operación, riesgo y posibilidad de reversa."]],
    ctaTitle: "Pon orden en la infraestructura que sostiene tu negocio.", ctaText: "Comparte el tipo de servidores, servicios críticos y principal preocupación operativa.", related: ["soporte-tecnico-empresas", "auditoria-ciberseguridad-nist", "equipos-componentes"],
  },
  {
    slug: "mantenimiento-equipos",
    eyebrow: "Mantenimiento tecnológico",
    title: "Mantenimiento de equipos de cómputo para empresas",
    description: "Mantenimiento preventivo y correctivo de equipos empresariales en CDMX y Estado de México: diagnóstico, limpieza, optimización y recuperación operativa.",
    intro: "El mantenimiento empresarial debe reducir fallas y tiempo perdido, no limitarse a limpiar equipos. IATERA revisa síntomas, uso, estado físico y sistema para recomendar una intervención proporcionada: mantenimiento preventivo, corrección, reemplazo de un componente o renovación del activo.",
    benefits: [["Diagnóstico primero", "La intervención parte de síntomas, pruebas y contexto de uso."], ["Trabajo trazable", "Se documentan hallazgos, acciones y componentes reemplazados."], ["Decisión proporcionada", "Comparamos reparación, mejora y sustitución según necesidad operativa."]],
    sections: [{ title: "Mantenimiento preventivo", text: "Programamos revisiones de limpieza, ventilación, almacenamiento, sistema y actualizaciones según el entorno y la intensidad de uso. La frecuencia se define por condiciones reales, no por una regla idéntica para todos." }, { title: "Diagnóstico y mantenimiento correctivo", text: "Ante lentitud, reinicios, temperatura, errores o fallas de arranque, aislamos la causa antes de reemplazar piezas. Si la reparación no es conveniente, explicamos las alternativas y sus implicaciones." }, { title: "Atención por lote o por incidente", text: "Podemos revisar un equipo que afecta a un usuario o coordinar una jornada para varios activos. En ambos casos se acuerdan recepción, respaldo de información, autorizaciones y criterios de entrega." }, { title: "Protección de la información", text: "Antes de manipular almacenamiento o sistema, definimos responsabilidades sobre respaldo y acceso. Cualquier recuperación depende del estado del medio y se cotiza con alcance específico." }],
    faq: [["¿Cada cuánto conviene dar mantenimiento?", "Depende del uso, polvo, temperatura, antigüedad y criticidad. Primero evaluamos el entorno y el historial de fallas."], ["¿El mantenimiento borra información?", "Una intervención normal no debería hacerlo, pero todo almacenamiento puede fallar. Recomendamos validar respaldos antes del servicio."], ["¿Reparan laptops y equipos de escritorio?", "Sí, sujeto a diagnóstico, disponibilidad de componentes y viabilidad económica."], ["¿Pueden atender varios equipos en una visita?", "Sí. Se organiza un inventario previo y una ventana que reduzca afectación a los usuarios."], ["¿Entregan reporte?", "El alcance puede incluir estado recibido, diagnóstico, acciones, pruebas y recomendaciones por activo."]],
    ctaTitle: "Evita que una falla pequeña detenga a un equipo.", ctaText: "Indica cuántos equipos requieren atención, sus síntomas y la ubicación.", related: ["equipos-componentes", "soporte-tecnico-empresas", "administracion-servidores"],
  },
  {
    slug: "equipos-componentes",
    eyebrow: "Equipamiento empresarial",
    title: "Equipos y componentes para empresas",
    description: "Suministro de equipos y componentes para empresas en México con validación de compatibilidad, configuración, instalación y pruebas.",
    intro: "Comprar tecnología sin revisar la carga de trabajo crea gasto, incompatibilidad y reemplazos prematuros. IATERA ayuda a seleccionar equipos o componentes a partir del uso, las aplicaciones, el crecimiento previsto y la infraestructura existente.",
    benefits: [["Selección por necesidad", "La recomendación parte de usuarios, aplicaciones y vida útil esperada."], ["Compatibilidad revisada", "Validamos formato, interfaz, capacidad y restricciones antes de instalar."], ["Entrega preparada", "Configuración, pruebas y migración pueden integrarse al alcance."]],
    sections: [{ title: "Equipos para el trabajo real", text: "Revisamos perfiles de uso para evitar especificaciones insuficientes o sobredimensionadas. La propuesta puede incluir laptops, desktops, periféricos o servidores, sujeta a disponibilidad del proveedor." }, { title: "Componentes compatibles", text: "Memoria, almacenamiento, baterías, fuentes, pantallas y otros repuestos se seleccionan después de identificar modelo, revisión, interfaz y requerimientos eléctricos o físicos." }, { title: "Nuevos, seminuevos o reacondicionados", text: "Cuando se consideran equipos no nuevos, explicamos condición, pruebas disponibles, garantía aplicable y limitaciones. No presentamos una categoría comercial como si garantizara por sí sola el estado del activo." }, { title: "Configuración, instalación y entrega", text: "El alcance puede sumar instalación, actualización, migración y pruebas con el usuario. Los accesos, licencias y respaldos necesarios se acuerdan antes del trabajo." }],
    faq: [["¿Venden a empresas de cualquier tamaño?", "Atendemos solicitudes empresariales según producto, cantidad, ubicación y disponibilidad."], ["¿Cómo confirman que un componente es compatible?", "Revisamos modelo exacto, especificaciones del fabricante, formato, interfaz y capacidad admitida."], ["¿Incluyen instalación?", "Puede incluirse en la propuesta junto con pruebas y documentación del reemplazo."], ["¿Manejan equipos reacondicionados?", "Podemos evaluar opciones cuando existan condiciones y garantía claramente informadas."], ["¿Ayudan a migrar la información?", "Sí, cuando el estado del equipo origen, el volumen y los accesos permiten definir un alcance seguro."], ["¿Publican precios fijos?", "No siempre, porque disponibilidad, garantía y especificaciones cambian. Confirmamos la propuesta antes de la compra."]],
    ctaTitle: "Compra capacidad útil, no especificaciones aisladas.", ctaText: "Cuéntanos qué tareas debe resolver el equipo, cuántos usuarios lo necesitan y qué infraestructura ya existe.", related: ["mantenimiento-equipos", "administracion-servidores", "soporte-tecnico-empresas"],
  },
  {
    slug: "desarrollo-web-empresarial",
    eyebrow: "Desarrollo web para empresas",
    title: "Páginas web empresariales orientadas a negocio",
    description: "Desarrollo web empresarial en México con arquitectura clara, diseño responsive, rendimiento, accesibilidad y bases técnicas preparadas para SEO.",
    intro: "IATERA diseña y desarrolla sitios empresariales que explican con claridad qué ofrece la empresa, facilitan el contacto y pueden mantenerse sin acumular complejidad innecesaria. El trabajo parte de objetivos, audiencias y contenido real antes de definir componentes, integraciones y tecnología.",
    benefits: [["Objetivo antes que efectos", "La estructura responde a las decisiones que debe tomar el visitante y a la información que necesita para confiar."], ["Experiencia en cualquier pantalla", "La interfaz se revisa en móvil y escritorio, con navegación, contraste y formularios accesibles."], ["Base técnica mantenible", "Organizamos componentes, contenido y metadatos para facilitar futuras mejoras sin reconstruir el sitio."]],
    sections: [
      { title: "Arquitectura y contenido", text: "Definimos páginas, jerarquía y recorridos a partir de servicios, clientes objetivo y preguntas comerciales frecuentes. No inventamos testimonios, resultados ni diferenciadores que la empresa no pueda respaldar.", items: ["Mapa del sitio y navegación", "Jerarquía de títulos y mensajes", "Llamadas a la acción y formularios"] },
      { title: "Diseño y desarrollo responsive", text: "Construimos una interfaz coherente con la identidad de la empresa y validamos su comportamiento en distintos anchos de pantalla. Priorizamos HTML semántico, CSS mantenible y JavaScript solo cuando aporta una función real." },
      { title: "Rendimiento y accesibilidad", text: "Optimizamos imágenes, carga de recursos, estados de foco, contraste y estructura semántica. La revisión técnica ayuda a reducir fricción para usuarios y motores de búsqueda." },
      { title: "Publicación y evolución", text: "Preparamos redirecciones, metadatos, medición y verificación del sitio antes de publicar. Después, las nuevas secciones pueden incorporarse sobre una base documentada y consistente." },
    ],
    faq: [["¿Trabajan sitios nuevos y rediseños?", "Sí. Primero revisamos objetivos, contenido, tecnología actual y riesgos de migración para recomendar el alcance adecuado."], ["¿El sitio incluye versión móvil?", "Sí. El comportamiento responsive y la navegación táctil forman parte del desarrollo, no son un complemento posterior."], ["¿Pueden respetar una identidad visual existente?", "Sí. Podemos aplicar lineamientos existentes o definir un sistema visual digital dentro del alcance acordado."], ["¿Incluyen hosting y dominio?", "Podemos apoyar con la configuración, pero propiedad, renovaciones, accesos y costos de terceros se especifican por separado."], ["¿El desarrollo incluye SEO?", "Incluye fundamentos técnicos y semánticos. La investigación, estrategia editorial y seguimiento SEO continuo se definen como un servicio específico."]],
    ctaTitle: "Convierte tu sitio en una herramienta comercial clara.", ctaText: "Comparte el objetivo, las páginas necesarias y la tecnología actual para definir el siguiente paso.", related: ["seo-mexico", "soporte-tecnico-empresas", "auditoria-ciberseguridad-nist"],
  },
  {
    slug: "seo-mexico",
    eyebrow: "Posicionamiento SEO",
    title: "SEO en México para búsquedas con intención real",
    description: "Servicio SEO en México para empresas: diagnóstico técnico, arquitectura, contenido útil, SEO local y medición orientada a oportunidades relevantes.",
    intro: "IATERA ayuda a las empresas a construir visibilidad orgánica sobre una base medible. Revisamos cómo rastrean e interpretan el sitio los buscadores, qué necesita encontrar el cliente potencial y qué contenido puede responder con evidencia, sin prometer posiciones ni tráfico fuera de control.",
    benefits: [["Prioridades justificadas", "Cada recomendación se vincula con un problema técnico, una búsqueda relevante o una oportunidad de contenido."], ["Contenido con intención", "La estrategia conecta servicios reales con preguntas y decisiones de clientes potenciales en México."], ["Medición comprensible", "Definimos indicadores y eventos que permiten evaluar visibilidad, interacción y oportunidades comerciales."]],
    sections: [
      { title: "Diagnóstico SEO técnico", text: "Revisamos indexación, rastreo, canonicals, redirecciones, sitemap, metadatos, datos estructurados, rendimiento y experiencia móvil para ordenar incidencias por impacto.", items: ["Cobertura e indexación", "Arquitectura y enlazado interno", "Rendimiento y señales técnicas"] },
      { title: "Investigación y arquitectura", text: "Agrupamos búsquedas por intención y relación con la oferta. Después definimos qué página debe responder cada necesidad para evitar contenido duplicado o páginas que compiten entre sí." },
      { title: "Contenido útil y SEO local", text: "Desarrollamos briefs y mejoras de contenido basadas en preguntas reales, cobertura geográfica y capacidad de servicio. Los datos locales y comerciales se publican únicamente cuando la empresa los confirma." },
      { title: "Medición y mejora continua", text: "Configuramos una línea base y revisamos cambios con contexto. El posicionamiento depende también de competencia, demanda y decisiones de los buscadores, por lo que no ofrecemos garantías de una posición específica." },
    ],
    faq: [["¿Cuándo se ven resultados?", "Depende del estado del sitio, competencia, demanda, autoridad y velocidad de implementación. El alcance define qué señales se revisarán y con qué frecuencia."], ["¿Garantizan la primera posición?", "No. Ningún proveedor controla los resultados orgánicos; trabajamos sobre mejoras verificables y oportunidades relevantes."], ["¿Trabajan SEO local?", "Sí, cuando la empresa cuenta con datos reales de ubicación, cobertura y contacto que puedan mantenerse consistentes."], ["¿Incluye creación de contenido?", "Puede incluir investigación, briefs, edición o redacción según el alcance y la disponibilidad de especialistas internos para validar información."], ["¿Pueden corregir problemas técnicos?", "Sí. Podemos entregar recomendaciones o implementar cambios cuando tenemos acceso y el alcance contempla desarrollo."]],
    ctaTitle: "Construye visibilidad sobre una base que puedas medir.", ctaText: "Comparte tu sitio, mercados prioritarios y servicios principales para preparar un diagnóstico inicial.", related: ["desarrollo-web-empresarial", "auditoria-ciberseguridad-nist", "administracion-servidores"],
  },
] as const;

export const serviceBySlug = Object.fromEntries(servicePages.map((page) => [page.slug, page])) as Record<string, ServicePageData>;
